"""Fetch the pre-built RMSP demand from the demand-data GitHub release.

The demand (Pesquisa OD 2023 + CNEFE/Censo + GeoSampa) is generated by the separate
``subway-builder-rmsp-demand-data`` project and published as a release asset. RMSP no
longer generates demand itself — it just downloads ``demand_data.json.gz`` into
``data/build/`` so the special-demand and routing steps can run on it. ``RMSP_DEMAND_URL``
overrides the release asset (e.g. to pin a different version).
"""

from __future__ import annotations

import gzip
import json
import logging
import urllib.request

from rmsp.config import settings

log = logging.getLogger(__name__)


def fetch() -> None:
    """Download the published demand_data.json.gz into data/build/ (json + .gz)."""
    settings.ensure_dirs()
    url = settings.demand_release_url
    log.info("fetching demand: %s", url)
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req) as r:  # noqa: S310
        gz = r.read()
    raw = gzip.decompress(gz)
    demand = json.loads(raw)  # fail fast if the asset is not valid demand JSON
    (settings.build_dir / "demand_data.json").write_bytes(raw)
    (settings.build_dir / "demand_data.json.gz").write_bytes(gz)
    log.info(
        "demand -> demand_data.json (%.1f MB, %d points, %d pops)",
        len(raw) / 1e6, len(demand["points"]), len(demand["pops"]),
    )
